-- Create Schema
DROP TABLE IF EXISTS GCU.Users;
DROP TABLE IF EXISTS GCU.Posts;
DROP SCHEMA IF EXISTS GCU
RESTRICT;

CREATE SCHEMA GCU;

-- Create Tables
CREATE TABLE GCU.Users
(
	Email VARCHAR(200) NOT NULL,
	FirstName VARCHAR
	(50) NOT NULL,
	LastName VARCHAR
	(50) NOT NULL,
	UserName VARCHAR
	(50) NOT NULL,
	Password VARCHAR
	(200) NOT NULL,
	CONSTRAINT primary_key
PRIMARY KEY
(Email)
);

CREATE TABLE GCU.Posts
(
	ID INT NOT NULL
	GENERATED ALWAYS AS IDENTITY,
		Title VARCHAR
	(255) NOT NULL,
		AuthorFirstName VARCHAR
	(255) NOT NULL,
		AuthorLastName VARCHAR
	(255) NOT NULL,
		Content TEXT
	NOT NULL
	);
