-- Create Schema
DROP TABLE GCU.Users;
DROP TABLE GCU.Books;
DROP SCHEMA GCU
RESTRICT;

CREATE SCHEMA GCU;

-- Create Tables
CREATE TABLE GCU.Users
(
	Email VARCHAR(200) NOT NULL,
	FirstName VARCHAR
	(50) NOT NULL,
	MiddleInitial VARCHAR
	(2) NOT NULL,
	LastName VARCHAR
	(50) NOT NULL,
	UserName VARCHAR
	(50) NOT NULL,
	Password VARCHAR
	(200) NOT NULL,
	CONSTRAINT primary_key
PRIMARY KEY
(Email)
);

CREATE TABLE GCU.Books
(
	ID INT NOT NULL
	GENERATED ALWAYS AS IDENTITY,
		Title VARCHAR
	(255) NOT NULL,
		Author VARCHAR
	(255) NOT NULL,
		ISBN VARCHAR
	(255) NOT NULL,
		Publisher VARCHAR
	(255) NOT NULL
	);
