-- Create Schema
DROP TABLE GCU.Users;
DROP TABLE GCU.Posts;
DROP TABLE GCU.Tags;
DROP TABLE GCU.PostTags;
DROP SCHEMA GCU

RESTRICT;

CREATE SCHEMA GCU;

-- Create Tables
CREATE TABLE GCU.Users
(
	Email VARCHAR(200) NOT NULL,
	FirstName VARCHAR
	(50) NOT NULL,
	MiddleInitial VARCHAR
	(2) NOT NULL,
	LastName VARCHAR
	(50) NOT NULL,
	UserName VARCHAR
	(50) NOT NULL,
	Password VARCHAR
	(200) NOT NULL,
	CONSTRAINT primary_key
PRIMARY KEY
(Email)
);

CREATE TABLE GCU.Posts
(
	ID INT NOT NULL
	GENERATED ALWAYS AS IDENTITY,
		Title VARCHAR
	(255) NOT NULL,
		AuthorID VARCHAR
	(255) NOT NULL,
		Content VARCHAR NOT NULL,
		Created DATETIME NOT NULL,
		Updated DATETIME NOT NULL,
		Deleted DATETIME,
	CONSTRAINT foreign_key
	FOREIGN KEY
	(AuthorId) REFERENCES Users.Email
	);

	CREATE TABLE GCU.Tags
	(
		-- ID INT NOT NULL
		-- GENERATED ALWAYS AS IDENTITY,
		Name VARCHAR
		(30) NOT NULL,
		CONSTRAINT primary_key
		PRIMARY KEY
		(Name)
	);

	CREATE TABLE GCU.PostTags
	(
		PostID INT
			NOT NULL,
		TagID VARCHAR(30) NOT NULL,
		CONSTRAINT foreign_key1
	FOREIGN KEY (PostID) REFERENCES Posts.ID,
		CONSTRAINT foreign_key2
	FOREIGN KEY
		(TagID) REFERENCES Tags.Title
	)
